/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Fernando
 */
public class Cliente2V2 extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    /*
    Operador es un valor de tipo String que cambiara segun el operador que seleccionemos en nuestra interfaz para 
   `poder interpretarlo en el servidor
    */
    String operador=null;
    
    public Cliente2V2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSuma = new javax.swing.JButton();
        bResta = new javax.swing.JButton();
        bMulti = new javax.swing.JButton();
        bDivi = new javax.swing.JButton();
        bRaiz = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        bEnviar = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbNega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSuma.setText("Sumar(+)");
        bSuma.setMaximumSize(new java.awt.Dimension(110, 50));
        bSuma.setMinimumSize(new java.awt.Dimension(110, 50));
        bSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSumaActionPerformed(evt);
            }
        });
        getContentPane().add(bSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 90, 75));

        bResta.setText("Restar(-)");
        bResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRestaActionPerformed(evt);
            }
        });
        getContentPane().add(bResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 75));

        bMulti.setText("Multi(*)");
        bMulti.setMaximumSize(new java.awt.Dimension(100, 20));
        bMulti.setMinimumSize(new java.awt.Dimension(100, 20));
        bMulti.setPreferredSize(new java.awt.Dimension(110, 20));
        bMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultiActionPerformed(evt);
            }
        });
        getContentPane().add(bMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 90, 75));

        bDivi.setText("División(/)");
        bDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDiviActionPerformed(evt);
            }
        });
        getContentPane().add(bDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 90, 75));

        bRaiz.setText("Raiz(√)");
        bRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRaizActionPerformed(evt);
            }
        });
        getContentPane().add(bRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 90, 75));

        b1.setText("1");
        b1.setPreferredSize(new java.awt.Dimension(75, 75));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        b2.setText("2");
        b2.setPreferredSize(new java.awt.Dimension(75, 75));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        b3.setText("3");
        b3.setPreferredSize(new java.awt.Dimension(75, 75));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        b4.setText("4");
        b4.setPreferredSize(new java.awt.Dimension(75, 75));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        b6.setText("6");
        b6.setPreferredSize(new java.awt.Dimension(75, 75));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        b5.setText("5");
        b5.setPreferredSize(new java.awt.Dimension(75, 75));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        b9.setText("9");
        b9.setPreferredSize(new java.awt.Dimension(75, 75));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        b8.setText("8");
        b8.setPreferredSize(new java.awt.Dimension(75, 75));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        b7.setText("7");
        b7.setPreferredSize(new java.awt.Dimension(75, 75));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        b10.setText("0");
        b10.setPreferredSize(new java.awt.Dimension(75, 75));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        t1.setPreferredSize(new java.awt.Dimension(75, 50));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.setPreferredSize(new java.awt.Dimension(75, 50));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, -1));

        t2.setPreferredSize(new java.awt.Dimension(75, 50));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 31, 99, -1));

        bEnviar.setText("Enviar");
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(bEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 150, 75));

        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t4.setPreferredSize(new java.awt.Dimension(75, 50));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 31, 110, -1));

        jLabel1.setText("Resultado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 11, -1, -1));

        jbNega.setText("Negativo(-)");
        jbNega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNegaActionPerformed(evt);
            }
        });
        getContentPane().add(jbNega, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 90, 75));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultiActionPerformed
        /*
        Boton de multiplicar muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 103 e impide que se puedan dar a los otros botones una vez dado este.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t3.setText("*");
        operador="103";
        t1.setEditable(false);
        t1.setEnabled(false);
    }//GEN-LAST:event_bMultiActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(t1.isEditable()==true){
            t1.setText(t1.getText()+"1");
        }else{
            t2.setText(t2.getText()+"1");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(t1.isEditable()==true){
            
            t1.setText(t1.getText()+"2");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"2");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(t1.isEditable()==true){
            t1.setText(t1.getText()+"3");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"3");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(t1.isEditable()==true){
            t1.setText(t1.getText()+"4");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"4");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(t1.isEditable()==true){
            t1.setText(t1.getText()+"5");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"5");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       if(t1.isEditable()==true){
            t1.setText(t1.getText()+"6");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"6");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(t1.isEditable()==true){
            t1.setText(t1.getText()+"7");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"7");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(t1.isEditable()==true){
            t1.setText(t1.getText()+"8");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"8");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(t1.isEditable()==true){
            t1.setText(t1.getText()+"9");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"9");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        if(t1.isEditable()==true){
            t1.setText(t1.getText()+"0");
            jbNega.setEnabled(false);
        }else{
            t2.setText(t2.getText()+"0");
            jbNega.setEnabled(false);
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void bSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSumaActionPerformed
        /*
        Boton de sumar muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 101 e impide que se puedan dar a los otros botones una vez dado este.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t3.setText("+");
        operador="101";
        t1.setEditable(false);
        t1.setEnabled(false);
        jbNega.setEnabled(true);
    }//GEN-LAST:event_bSumaActionPerformed

    private void bRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRestaActionPerformed
        /*
        Boton de restar muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 102 e impide que se puedan dar a los otros botones una vez dado este.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t3.setText("-");
        operador="102";
        t1.setEditable(false);
        t1.setEnabled(false);
        jbNega.setEnabled(true);
    }//GEN-LAST:event_bRestaActionPerformed

    private void bDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDiviActionPerformed
        /*
        Boton de dividir muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 104 e impide que se puedan dar a los otros botones una vez dado este.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t3.setText("/");
        operador="104";
        t1.setEditable(false);
        t1.setEnabled(false);
        jbNega.setEnabled(true);
    }//GEN-LAST:event_bDiviActionPerformed

    private void bRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRaizActionPerformed
        /*
        Boton de la raiz muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 105 e impide que se puedan dar a los otros botones una vez dado este, 
        además a diferencia de los otros, tambien impide que se pueda escribir en el ultimo TextView porque la raiz solo 
        necesita un valor.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t3.setText("Raiz");
        operador="105";
        t1.setEditable(false);
        t1.setEnabled(false);
        t2.setEditable(false);
        t2.setEnabled(false);
        t3.setEnabled(false);
        
    }//GEN-LAST:event_bRaizActionPerformed

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        try{
            /*
            Abrimos el socket del cliente y establecemos la conexión con el host del servidor
            ademas creamos ya nuestros Inputs y Outputs Stream que usaremos
            */
            System.out.println("Creando socket cliente");
            Socket clienteSocket=new Socket();
            System.out.println("Estableciendo la conexion");
            InetSocketAddress addr=new InetSocketAddress(JOptionPane.showInputDialog("Dime la direccion IP a la que quieres conectarte:"),Integer.parseInt(JOptionPane.showInputDialog("Dime el numero de puerto:")));
            clienteSocket.connect(addr);
            
            InputStream is = clienteSocket.getInputStream();
            OutputStream os= clienteSocket.getOutputStream();
            /*
            Usamos el if para distinguir la raiz del resto de operadores ya que esta solo pasara dos datos en el array y no tres
            */
            
            if(operador=="105"){
            String []operacion={t1.getText(),operador};
            for(int i=0;i<=1;i++){   
            os.write(Byte.valueOf(operacion[i]));   
            }
            os.write(0);
            }else{
                /*
                Creamos un array de string donde mandamos el primer digito, luego el operador y por ultimo el segundo digito a operar
                despues creamos un for para mandar estos datos en orden y que al leerlos en el servidor puedan ser tratados
                */
            String []operacion={t1.getText(),operador,t2.getText()};
            for(int i=0;i<=2;i++){ 
            
            os.write(Byte.valueOf(operacion[i]));  
            
            }
            //Mandamos los mensajes
            os.write(0);
            }
            
            /*
            Creamos un dato de tipo byte con el que leeremos el resultado que nos llegue desde el servidor y que
            sera mostrado en la interfaz en el apartado del resultado.
            */
            byte[]result=new byte[50];
            is.read(result);
            t4.setText(new String (result));
            System.out.println(new String(result));
            /*
            Despues cerramos el socket.
            */
            System.out.println("Cerrando el socket cliente");

            clienteSocket.close();

            System.out.println("Terminado");
            
            }catch (IOException e) {
                e.printStackTrace();
        }
    }//GEN-LAST:event_bEnviarActionPerformed

    private void jbNegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNegaActionPerformed
        if(t1.getText()==null){
            if(t1.isEditable()==true){
                t1.setText("-");
            }else{
             t2.setText("-");
        }
        }else if(t2.getText()==null){
            if(t1.isEditable()==true){
                t1.setText("-");
            }else{
                t2.setText("-");
        }
        }
        
    }//GEN-LAST:event_jbNegaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente2V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente2V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente2V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente2V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente2V2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bDivi;
    private javax.swing.JButton bEnviar;
    private javax.swing.JButton bMulti;
    private javax.swing.JButton bRaiz;
    private javax.swing.JButton bResta;
    private javax.swing.JButton bSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbNega;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
